controller_manager:
  ros__parameters:
    update_rate: 5  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - front_left_body_link_to_coxa_link_joint
      - front_left_coxa_link_to_femur_link_joint
      - front_left_femur_link_to_tibia_link_joint
      # - front_right_body_link_to_coxa_link_joint
      # - front_right_coxa_link_to_femur_link_joint
      # - front_right_femur_link_to_tibia_link_joint
      # - rear_left_body_link_to_coxa_link_joint
      # - rear_left_coxa_link_to_femur_link_joint
      # - rear_left_femur_link_to_tibia_link_joint
      # - rear_right_body_link_to_coxa_link_joint
      # - rear_right_coxa_link_to_femur_link_joint
      # - rear_right_femur_link_to_tibia_link_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 30.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      front_left_body_link_to_coxa_link_joint: { trajectory: 0.2, goal: 0.1 }
      front_left_coxa_link_to_femur_link_joint: { trajectory: 0.2, goal: 0.1 }
      front_left_femur_link_to_tibia_link_joint: { trajectory: 0.2, goal: 0.1 }
      # front_right_body_link_to_coxa_link_joint: { trajectory: 0.2, goal: 0.1 }
      # front_right_coxa_link_to_femur_link_joint: { trajectory: 0.2, goal: 0.1 }
      # front_right_femur_link_to_tibia_link_joint: { trajectory: 0.2, goal: 0.1 }
      # rear_left_body_link_to_coxa_link_joint: { trajectory: 0.2, goal: 0.1 }
      # rear_left_coxa_link_to_femur_link_joint: { trajectory: 0.2, goal: 0.1 }
      # rear_left_femur_link_to_tibia_link_joint: { trajectory: 0.2, goal: 0.1 }
      # rear_right_body_link_to_coxa_link_joint: { trajectory: 0.2, goal: 0.1 }
      # rear_right_coxa_link_to_femur_link_joint: { trajectory: 0.2, goal: 0.1 }
      # rear_right_femur_link_to_tibia_link_joint: { trajectory: 0.2, goal: 0.1 }