version: "3.4"

services:
  balltze_description:
    build:
      context: ./../../
      dockerfile: ./examples/Dockerfile
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../../balltze_description:/ros2_ws/src/balltze_description:rw
    command: ros2 launch balltze_description rviz.launch.py
    