<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- LEG MACRO -->
  <xacro:macro name="leg" params="leg_prefix robot_width robot_length">

    <xacro:property name="link_1_to_link_2_x" value="0.0" />
    <xacro:property name="link_1_to_link_2_y" value="0.06" />
    <xacro:property name="link_1_to_link_2_z" value="0.0" />
    <xacro:macro name="link_1_inertial">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
    </xacro:macro>

    <xacro:property name="link_2_to_link_3_x" value="0.0" />
    <xacro:property name="link_2_to_link_3_y" value="0.0" />
    <xacro:property name="link_2_to_link_3_z" value="-0.11" />
    <xacro:macro name="link_2_inertial">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
    </xacro:macro>

    <xacro:property name="link_3_to_tip_x" value="0.15" />
    <xacro:property name="link_3_to_tip_y" value="0.0" />
    <xacro:property name="link_3_to_tip_z" value="0.0" />
    <xacro:macro name="link_3_inertial">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>
    </xacro:macro>

    <xacro:property name="motor_range"   value="${300.0 / 360.0 * (2.0 * pi)}" />
    <xacro:property name="motor_max_vel" value="${114.0 * (2.0 * pi / 60.0)}" />
    <xacro:property name="motor_max_eff" value="1.5" />

    <!-- CONDITIONAL BLOCKS -->
    <xacro:if value="${leg_prefix == 'fl'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_link_1_xyz" value="${robot_length/2.0} ${robot_width/2.0} 0.0" />
      <xacro:property name="link_1_to_link_2_xyz" value="${link_1_to_link_2_x} ${link_1_to_link_2_y} ${link_1_to_link_2_z}" />
      <xacro:property name="link_2_to_link_3_xyz" value="${link_2_to_link_3_x} ${link_2_to_link_3_y} ${link_2_to_link_3_z}" />
      <xacro:property name="link_3_to_tip_xyz" value="${link_3_to_tip_x} ${link_3_to_tip_y} ${link_3_to_tip_z}" />
    </xacro:if>
    <xacro:if value="${leg_prefix == 'fr'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_link_1_xyz" value="${robot_length/2.0} -${robot_width/2.0} 0.0" />
      <xacro:property name="link_1_to_link_2_xyz" value="${link_1_to_link_2_x} -${link_1_to_link_2_y} 0.0" />
      <xacro:property name="link_2_to_link_3_xyz" value="${link_2_to_link_3_x} -${link_2_to_link_3_y} ${link_2_to_link_3_z}" />
      <xacro:property name="link_3_to_tip_xyz" value="${link_3_to_tip_x} -${link_3_to_tip_y} ${link_3_to_tip_z}" />
    </xacro:if>
    <xacro:if value="${leg_prefix == 'rl'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_link_1_xyz" value="-${robot_length/2.0} ${robot_width/2.0} 0.0" />
      <xacro:property name="link_1_to_link_2_xyz" value="${link_1_to_link_2_x} ${link_1_to_link_2_y} 0.0" />
      <xacro:property name="link_2_to_link_3_xyz" value="${link_2_to_link_3_x} ${link_2_to_link_3_y} ${link_2_to_link_3_z}" />
      <xacro:property name="link_3_to_tip_xyz" value="${link_3_to_tip_x} ${link_3_to_tip_y} ${link_3_to_tip_z}" />
    </xacro:if>
    <xacro:if value="${leg_prefix == 'rr'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_link_1_xyz" value="-${robot_length/2.0} -${robot_width/2.0} 0.0" />
      <xacro:property name="link_1_to_link_2_xyz" value="${link_1_to_link_2_x} -${link_1_to_link_2_y} 0.0" />
      <xacro:property name="link_2_to_link_3_xyz" value="${link_2_to_link_3_x} -${link_2_to_link_3_y} ${link_2_to_link_3_z}" />
      <xacro:property name="link_3_to_tip_xyz" value="${link_3_to_tip_x} -${link_3_to_tip_y} ${link_3_to_tip_z}" />
    </xacro:if>

    
    <!-- LEG LINK -->
    <xacro:macro name="leg_link" params="leg_prefix side link_name **inertial">     

      <!-- LINK DEFINITION -->
      <link name="${leg_prefix}_${link_name}">
        <visual>
          <geometry>
            <sphere radius="0.02"/>
            <!-- <mesh filename="file://$(find balltze_description)/meshes/${side}_${link_name}.stl" scale="0.1 0.1 0.1" /> -->
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </visual>

        <collision>
          <geometry>
            <sphere radius="0.02"/>
            <!-- <mesh filename="file://$(find balltze_description)/meshes/${side}_${link_name}_collision.stl" scale="0.1 0.1 0.1" /> -->
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>

        <inertial>
          <xacro:insert_block name="inertial" />
        </inertial>
      </link>
    </xacro:macro>


    <!-- LEG JOINT -->
    <xacro:macro name="leg_joint" params="leg_prefix joint_name parent child xyz axis joint_min joint_max">
      <!-- JOINT DEFINITION -->
      <joint name="${leg_prefix}_${joint_name}" type="revolute">
        <xacro:if value="${parent == 'body_link'}">
          <parent link="${parent}" />
        </xacro:if>
        <xacro:unless value="${parent == 'body_link'}">
          <parent link="${leg_prefix}_${parent}" />
        </xacro:unless>
        <child link="${leg_prefix}_${child}" />
        
        <origin xyz="${xyz}" rpy="0.0 0.0 0.0" />
        <axis xyz="${axis}" />

        <dynamics damping="0.0"/>

        <limit effort="${motor_max_eff}"
               lower="${joint_min}"
               upper="${joint_max}"
               velocity="${motor_max_vel}" />
      </joint>
    </xacro:macro>

    <!-- DEFINE LINKS -->
    <xacro:leg_link leg_prefix="${leg_prefix}" side="${side}" link_name="link_1">
      <xacro:link_1_inertial/>
    </xacro:leg_link>

    <xacro:leg_link leg_prefix="${leg_prefix}" side="${side}" link_name="link_2">
      <xacro:link_2_inertial/>
    </xacro:leg_link>

    <xacro:leg_link leg_prefix="${leg_prefix}" side="${side}" link_name="link_3">
      <xacro:link_3_inertial/>
    </xacro:leg_link>

    <link name="${leg_prefix}_tip">
      <visual>
        <geometry>
          <sphere radius="0.02"/>
          <!-- <mesh filename="file://$(find balltze_description)/meshes/${side}_link_1.stl" scale="0.1 0.1 0.1" /> -->
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </visual>

      <collision name="${leg_prefix}_tip">
        <geometry>
          <sphere radius="0.02"/>
          <!-- <mesh filename="file://$(find balltze_description)/meshes/${side}_link_1_collision.stl" scale="0.1 0.1 0.1" /> -->
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </collision>
    </link>


    <!-- DEFINE JOINTS -->
    <xacro:leg_joint
      leg_prefix="${leg_prefix}"
      joint_name="joint_1"
      parent="body_link"
      child="link_1"
      xyz="${body_to_link_1_xyz}"
      axis="1 0 0"
      joint_min="${-pi/4.0}"
      joint_max="${pi/4.0}"
    />

    <xacro:leg_joint
      leg_prefix="${leg_prefix}"
      joint_name="joint_2"
      parent="link_1"
      child="link_2"
      xyz="${link_1_to_link_2_xyz}"
      axis="0 1 0"
      joint_min="${-pi/2.0}"
      joint_max="${pi/2.0}"
    />

    <xacro:leg_joint
      leg_prefix="${leg_prefix}"
      joint_name="joint_3"
      parent="link_2"
      child="link_3"
      xyz="${link_2_to_link_3_xyz}"
      axis="0 1 0"
      joint_min="${-pi/2.0}"
      joint_max="${pi/2.0}"
    />

    <joint name="${leg_prefix}_joint_4" type="fixed">
      <parent link="${leg_prefix}_link_3" />
      <child link="${leg_prefix}_tip" />
      <origin xyz="${link_3_to_tip_xyz}" rpy="0.0 0.0 0.0" />
    </joint>

    <gazebo reference="${leg_prefix}_tip">
      <sensor name='${leg_prefix}_contact_system' type='contact'>
        <contact>
          <topic>/balltze/${leg_prefix}_tip/contact</topic>
          <!-- how not to love ignition gazebo's static transforms... -->
          <collision>${leg_prefix}_link_3_fixed_joint_lump__${leg_prefix}_tip_collision_1</collision>
        </contact>
      </sensor>
    </gazebo>

  </xacro:macro>

</robot>
