<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- LEG MACRO -->
  <xacro:macro name="leg" params="leg_prefix robot_width robot_length">

    <xacro:property name="coxa_to_femur_x" value="0.0" />
    <xacro:property name="coxa_to_femur_y" value="0.06" />
    <xacro:property name="coxa_to_femur_z" value="0.0" />
    <xacro:macro name="coxa_inertial">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      </inertial>
    </xacro:macro>

    <xacro:property name="femur_to_tibia_x" value="0.0" />
    <xacro:property name="femur_to_tibia_y" value="0.0" />
    <xacro:property name="femur_to_tibia_z" value="-0.11" />
    <xacro:macro name="femur_inertial">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      </inertial>
    </xacro:macro>

    <xacro:property name="tibia_to_tip_x" value="0.15" />
    <xacro:property name="tibia_to_tip_y" value="0.0" />
    <xacro:property name="tibia_to_tip_z" value="0.0" />
    <xacro:macro name="tibia_inertial">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      </inertial>
    </xacro:macro>

    <xacro:property name="motor_range"   value="${300.0 / 360.0 * (2.0 * pi)}" />
    <xacro:property name="motor_max_vel" value="${114.0 * (2.0 * pi / 60.0)}" />
    <xacro:property name="motor_max_eff" value="1.5" />

    <!-- CONDITIONAL BLOCKS -->
    <xacro:if value="${leg_prefix == 'front_left'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_coxa_xyz" value="${robot_length/2.0} ${robot_width/2.0} 0.0" />
      <xacro:property name="coxa_to_femur_xyz" value="${coxa_to_femur_x} ${coxa_to_femur_y} ${coxa_to_femur_z}" />
      <xacro:property name="femur_tibia_xyz" value="${femur_to_tibia_x} ${femur_to_tibia_y} ${femur_to_tibia_z}" />
      <xacro:property name="tibia_tip_xyz" value="${tibia_to_tip_x} ${tibia_to_tip_y} ${tibia_to_tip_z}" />
    </xacro:if>
    <xacro:if value="${leg_prefix == 'front_right'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_coxa_xyz" value="${robot_length/2.0} -${robot_width/2.0} 0.0" />
      <xacro:property name="coxa_to_femur_xyz" value="${coxa_to_femur_x} -${coxa_to_femur_y} 0.0" />
      <xacro:property name="femur_tibia_xyz" value="${femur_to_tibia_x} -${femur_to_tibia_y} ${femur_to_tibia_z}" />
      <xacro:property name="tibia_tip_xyz" value="${tibia_to_tip_x} -${tibia_to_tip_y} ${tibia_to_tip_z}" />
    </xacro:if>
    <xacro:if value="${leg_prefix == 'rear_left'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_coxa_xyz" value="-${robot_length/2.0} ${robot_width/2.0} 0.0" />
      <xacro:property name="coxa_to_femur_xyz" value="${coxa_to_femur_x} ${coxa_to_femur_y} 0.0" />
      <xacro:property name="femur_tibia_xyz" value="${femur_to_tibia_x} ${femur_to_tibia_y} ${femur_to_tibia_z}" />
      <xacro:property name="tibia_tip_xyz" value="${tibia_to_tip_x} ${tibia_to_tip_y} ${tibia_to_tip_z}" />
    </xacro:if>
    <xacro:if value="${leg_prefix == 'rear_right'}">
      <xacro:property name="side" value="left" />
      <xacro:property name="body_to_coxa_xyz" value="-${robot_length/2.0} -${robot_width/2.0} 0.0" />
      <xacro:property name="coxa_to_femur_xyz" value="${coxa_to_femur_x} -${coxa_to_femur_y} 0.0" />
      <xacro:property name="femur_tibia_xyz" value="${femur_to_tibia_x} -${femur_to_tibia_y} ${femur_to_tibia_z}" />
      <xacro:property name="tibia_tip_xyz" value="${tibia_to_tip_x} -${tibia_to_tip_y} ${tibia_to_tip_z}" />
    </xacro:if>

    
    <!-- LEG LINK -->
    <xacro:macro name="leg_link" params="leg_prefix side link_name **inertial">     

      <!-- LINK DEFINITION -->
      <link name="${leg_prefix}_${link_name}">
        <visual>
          <geometry>
            <mesh filename="file://$(find balltze_description)/meshes/${side}_${link_name}.stl" scale="0.1 0.1 0.1" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </visual>

        <collision>
          <geometry>
            <mesh filename="file://$(find balltze_description)/meshes/${side}_${link_name}_collision.stl" scale="0.1 0.1 0.1" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>

        <inertial>
          <xacro:insert_block name="inertial" />
        </inertial>
      </link>
    </xacro:macro>


    <!-- LEG JOINT -->
    <xacro:macro name="leg_joint" params="leg_prefix parent child xyz axis">
      <!-- JOINT DEFINITION -->
      <joint name="${leg_prefix}_${parent}_to_${child}_joint" type="revolute">
        <xacro:if value="${parent == 'body_link'}">
          <parent link="${parent}" />
        </xacro:if>
        <xacro:unless value="${parent == 'body_link'}">
          <parent link="${leg_prefix}_${parent}" />
        </xacro:unless>
        <child link="${leg_prefix}_${child}" />
        
        <origin xyz="${xyz}" rpy="0.0 0.0 0.0" />
        <axis xyz="${axis}" />

        <dynamics damping="0.2"/>

        <limit effort="${motor_max_eff}"
               lower="${-motor_range/2.0}"
               upper="${motor_range/2.0}"
               velocity="${motor_max_vel}" />
      </joint>
    </xacro:macro>

    <!-- DEFINE LINKS -->
    <xacro:leg_link leg_prefix="${leg_prefix}" side="${side}" link_name="coxa_link">
      <xacro:coxa_inertial/>
    </xacro:leg_link>

    <xacro:leg_link leg_prefix="${leg_prefix}" side="${side}" link_name="femur_link">
      <xacro:femur_inertial/>
    </xacro:leg_link>

    <xacro:leg_link leg_prefix="${leg_prefix}" side="${side}" link_name="tibia_link">
      <xacro:tibia_inertial/>
    </xacro:leg_link>

    <link name="${leg_prefix}_tip_link">
      <visual>
        <geometry>
          <mesh filename="file://$(find balltze_description)/meshes/${side}_coxa_link.stl" scale="0.1 0.1 0.1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </visual>

      <collision>
        <geometry>
          <mesh filename="file://$(find balltze_description)/meshes/${side}_coxa_link_collision.stl" scale="0.1 0.1 0.1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </collision>
    </link>


    <!-- DEFINE JOINTS -->
    <xacro:leg_joint
      leg_prefix="${leg_prefix}"
      parent="body_link"
      child="coxa_link"
      xyz="${body_to_coxa_xyz}"
      axis="1 0 0"
    />

    <xacro:leg_joint
      leg_prefix="${leg_prefix}"
      parent="coxa_link"
      child="femur_link"
      xyz="${coxa_to_femur_xyz}"
      axis="0 1 0"
    />

    <xacro:leg_joint
      leg_prefix="${leg_prefix}"
      parent="femur_link"
      child="tibia_link"
      xyz="${femur_tibia_xyz}"
      axis="0 1 0"
    />

    <joint name="${leg_prefix}_tibia_link_to_tip_link_joint" type="fixed">
      <parent link="${leg_prefix}_tibia_link" />
      <child link="${leg_prefix}_tip_link" />
      <origin xyz="${tibia_tip_xyz}" rpy="0.0 0.0 0.0" />
    </joint>

  </xacro:macro>

</robot>
