services:
  workspace:
    build: .
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    runtime: nvidia
    stdin_open: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/ros2_ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev:/dev
    environment:
      - DISPLAY
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display