version: "3.4"

services:
  balltze_description:
    build:
      context: ./../../
      dockerfile: ./examples/Dockerfile
    environment:
      - "DISPLAY=host.docker.internal:0.0"
    volumes:
      - ./../../balltze_description/:/ros2_ws/src/balltze_description/:rw
    command: ros2 launch balltze_description rviz.launch.py
    