<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- LEG MACRO -->
  <xacro:macro name="leg" params="leg_prefix props use_ros_path">

    <xacro:property name="robot_props" value="${props}" />

    <!-- LEG LINK -->
    <xacro:macro name="leg_link" params="props">

      <!-- CONDITIONAL BLOCKS -->
      <xacro:if value="${leg_prefix == 'fr'}">
        <xacro:property name="visual_mesh_props" value="${props['link']['mesh'][0]}" />
        <xacro:property name="collision_mesh_props" value="${props['link']['collision'][0]}" />
        <xacro:property name="length_props" value="${props['link']['length'][0]}" />
        <xacro:property name="width_props" value="${props['link']['width'][0]}" />
        <xacro:property name="origin_porps" value="${props['link']['origin'][0]}" />
        <xacro:property name="mass_porps" value="${props['link']['mass'][0]}" />
        <xacro:property name="inertia_porps" value="${props['link']['inertia'][0]}" />
      </xacro:if>
      <xacro:if value="${leg_prefix == 'fl'}">
        <xacro:property name="visual_mesh_props" value="${props['link']['mesh'][1]}" />
        <xacro:property name="collision_mesh_props" value="${props['link']['collision'][1]}" />
        <xacro:property name="length_props" value="${props['link']['length'][1]}" />
        <xacro:property name="width_props" value="${props['link']['width'][1]}" />
        <xacro:property name="origin_porps" value="${props['link']['origin'][1]}" />
        <xacro:property name="mass_porps" value="${props['link']['mass'][1]}" />
        <xacro:property name="inertia_porps" value="${props['link']['inertia'][1]}" />
      </xacro:if>
      <xacro:if value="${leg_prefix == 'rr'}">
        <xacro:property name="visual_mesh_props" value="${props['link']['mesh'][2]}" />
        <xacro:property name="collision_mesh_props" value="${props['link']['collision'][2]}" />
        <xacro:property name="length_props" value="${props['link']['length'][2]}" />
        <xacro:property name="width_props" value="${props['link']['width'][2]}" />
        <xacro:property name="origin_porps" value="${props['link']['origin'][2]}" />
        <xacro:property name="mass_porps" value="${props['link']['mass'][2]}" />
        <xacro:property name="inertia_porps" value="${props['link']['inertia'][2]}" />
      </xacro:if>
      <xacro:if value="${leg_prefix == 'rl'}">
        <xacro:property name="visual_mesh_props" value="${props['link']['mesh'][3]}" />
        <xacro:property name="collision_mesh_props" value="${props['link']['collision'][3]}" />
        <xacro:property name="length_props" value="${props['link']['length'][3]}" />
        <xacro:property name="width_props" value="${props['link']['width'][3]}" />
        <xacro:property name="origin_porps" value="${props['link']['origin'][3]}" />
        <xacro:property name="mass_porps" value="${props['link']['mass'][3]}" />
        <xacro:property name="inertia_porps" value="${props['link']['inertia'][3]}" />
      </xacro:if>

      <!-- LINK DEFINITION -->
      <link name="${leg_prefix}_${props['name']}">
        <visual>
          <geometry>
            <xacro:property name="mesh" value="${visual_mesh_props}" />
            <xacro:if value="${mesh == 'None'}">
              <box size="${length_props}
                         ${width_props}
                         ${width_props}" />
            </xacro:if>

            <xacro:unless value="${mesh == 'None'}">
              <xacro:if value="${use_ros_path}">
                <mesh filename="$(find balltze_description)/meshes/${mesh}" scale="1 1 1" />
              </xacro:if>
              <xacro:unless value="${use_ros_path}">
                <mesh filename="$(cwd)/meshes/${mesh}" scale="1 1 1" />
              </xacro:unless>
            </xacro:unless>
          </geometry>
          
          <origin xyz="${origin_porps['x']} ${origin_porps['y']} ${origin_porps['z']}"
                  rpy="${pi/2} 0 0" />
        </visual>

        <collision>
          <xacro:property name="mesh" value="${collision_mesh_props}" />
          <xacro:if value="${mesh == 'None'}">
            <geometry>
              <sphere radius="${width_props/2}"/>
            </geometry>
            <origin xyz="${length_props - width_props/2} 0 0"
                  rpy="0 0 0" />
          </xacro:if>
          <xacro:unless value="${mesh == 'None'}">
            <geometry>
                <xacro:if value="${use_ros_path}">
                  <mesh filename="$(find balltze_description)/meshes/${mesh}" scale="1 1 1" />
                </xacro:if>
                <xacro:unless value="${use_ros_path}">
                  <mesh filename="$(cwd)/meshes/${mesh}" scale="1 1 1" />
                </xacro:unless>
            </geometry>
            <origin xyz="${origin_porps['x']} ${origin_porps['y']} ${origin_porps['z']}"
                    rpy="0 0 0" />
          </xacro:unless>
        </collision>

        <inertial>
          <mass value="${mass_porps}" />
          <inertia ixx="${inertia_porps['ixx']}"
                   ixy="${inertia_porps['ixy']}"
                   ixz="${inertia_porps['ixz']}"
                   iyy="${inertia_porps['iyy']}"
                   iyz="${inertia_porps['iyz']}"
                   izz="${inertia_porps['izz']}" />
        </inertial>

        <contact>
          <friction_anchor/>
          <stiffness value="30000.0"/>
          <damping value="1000.0"/>
          <spinning_friction value="0.3"/>
          <lateral_friction value="3.0"/>
        </contact>
      </link>
    </xacro:macro>



    <!-- LEG JOINT -->
    <xacro:macro name="leg_joint" params="props parent_name axis rotation">

      <!-- CONDITIONAL BLOCKS -->
      <xacro:property name="velocity_props" value="${props['joint']['velocity']}" />
      <xacro:property name="effort_props" value="${props['joint']['effort']}" />
      <xacro:if value="${leg_prefix == 'fr'}">
        <xacro:property name="origin_porps" value="${props['joint']['origin'][0]}" />
        <xacro:property name="lower_limit_props" value="${props['joint']['limit']['lower'][0]}" />
        <xacro:property name="upper_limit_props" value="${props['joint']['limit']['upper'][0]}" />
        <xacro:property name="damping_porps" value="${props['joint']['damping'][0]}" />
        <xacro:property name="friction_porps" value="${props['joint']['friction'][0]}" />
      </xacro:if>
      <xacro:if value="${leg_prefix == 'fl'}">
        <xacro:property name="origin_porps" value="${props['joint']['origin'][1]}" />
        <xacro:property name="lower_limit_props" value="${props['joint']['limit']['lower'][1]}" />
        <xacro:property name="upper_limit_props" value="${props['joint']['limit']['upper'][1]}" />
        <xacro:property name="damping_porps" value="${props['joint']['damping'][1]}" />
        <xacro:property name="friction_porps" value="${props['joint']['friction'][1]}" />
      </xacro:if>
      <xacro:if value="${leg_prefix == 'rr'}">
        <xacro:property name="origin_porps" value="${props['joint']['origin'][2]}" />
        <xacro:property name="lower_limit_props" value="${props['joint']['limit']['lower'][2]}" />
        <xacro:property name="upper_limit_props" value="${props['joint']['limit']['upper'][2]}" />
        <xacro:property name="damping_porps" value="${props['joint']['damping'][2]}" />
        <xacro:property name="friction_porps" value="${props['joint']['friction'][2]}" />
      </xacro:if>
      <xacro:if value="${leg_prefix == 'rl'}">
        <xacro:property name="origin_porps" value="${props['joint']['origin'][3]}" />
        <xacro:property name="lower_limit_props" value="${props['joint']['limit']['lower'][3]}" />
        <xacro:property name="upper_limit_props" value="${props['joint']['limit']['upper'][3]}" />
        <xacro:property name="damping_porps" value="${props['joint']['damping'][3]}" />
        <xacro:property name="friction_porps" value="${props['joint']['friction'][3]}" />
      </xacro:if>

      <!-- JOINT DEFINITION -->
      <joint name="${leg_prefix}_${parent_name}_to_${props['name']}_joint"
             type="revolute">

        <xacro:if value="${parent_name == 'base_link'}">
          <parent link="${parent_name}" />
        </xacro:if>
        <xacro:unless value="${parent_name == 'base_link'}">
          <parent link="${leg_prefix}_${parent_name}" />
        </xacro:unless>
        <origin xyz="${origin_porps['x']} ${origin_porps['y']} ${origin_porps['z']}"
                rpy="${rotation}" />

        <child link="${leg_prefix}_${props['name']}" />
        <axis xyz="${axis}" />

        <limit effort="${effort_props}"
               lower="${lower_limit_props}"
               upper="${upper_limit_props}"
               velocity="${velocity_props}" />

        <dynamics damping="${damping_porps}"
                  friction="${friction_porps}"/>

      </joint>



    </xacro:macro>

    <!-- DEFINE LINKS -->
    <xacro:leg_link props="${robot_props['coxa']}" />
    <xacro:leg_link props="${robot_props['femur']}" />
    <xacro:leg_link props="${robot_props['tibia']}" />

    <!-- DEFINE JOINTS -->
    <xacro:leg_joint props="${robot_props['coxa']}"
                     parent_name="base_link"
                     axis="1 0 0"
                     rotation="0 0 0" />

    <xacro:leg_joint props="${robot_props['femur']}"
                     parent_name="coxa"
                     axis="0 -1 0"
                     rotation="0 ${pi/2} 0" />

    <xacro:leg_joint props="${robot_props['tibia']}"
                     parent_name="femur"
                     axis="0 -1 0"
                     rotation="0 0 0" />

  </xacro:macro>

</robot>
